const createChildRouter = require('./childResource');

module.exports = createChildRouter({
  table: 'infrastructure_items',
  columns: [
    'category',
    'subtype',
    'manufacturer',
    'model',
    'serial_number',
    'firmware_version',
    'operating_system',
    'form_factor',
    'hostname',
    'ip_address',
    'location_description',
    'install_date',
    'end_of_life_date',
    'warranty_end_date',
    'condition',
    'details',
    'server_type',
    'hypervisor_type',
    'host_infrastructure_item_id',
    'domain_joined',
    'server_roles',
    'mac_address',
    'managed_print_contract',
    'asset_tag',
    'raid_level',
    'total_capacity',
    'drive_count',
    'connection_type',
    'notes',
  ],
});
